Repository KiranPolaki/GuessTheNumber, pull requests merged in 2023-10, with the labels that each got.

#6 Added favicon
  images/guess number.png
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#10 highScore is now persistent till the session ends.
  script.js
Labels: enhancement

#12 secret number is revealed after player loses the game
  script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#18 Added responsiveness for mobile devices
  style.css
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted

#30 Update newContributor.html
  newContributor.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#23 add auto reload page
  newContributor.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#34 Fixed Bug in script.js
  script.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#35 Fixed Reloading
  script.js
Labels: bug, hacktoberfest, hacktoberfest-accepted
